_target_: src.losses.components.alignment.AlignmentLoss
scale: 1.0
reduction: mean # "mean", "sum", "none"

margin: 1.0
distance: l2 # "l2", "l1", "cosine", "wasserstein"
strategy: push_simulations # "push_simulations", "cluster_zerobias", "contrastive"