[project]
name = "adatl1"
version = "0.1.0"
description = "Anomaly detection at the L1 trigger."
authors = [
    {name = "Victor Jimenez Rodriguez",email = "victor.jimenez.rodriguez@estudiantat.upc.edu"}
]
readme = "README.md"
requires-python = "^3.9"
dependencies = [
    "aiohappyeyeballs (>=2.6.1,<3.0.0)",
    "aiohttp (>=3.11.14,<4.0.0)",
    "aiosignal (>=1.3.2,<2.0.0)",
    "alembic (>=1.15.1,<2.0.0)",
    "annotated-types (>=0.7.0,<0.8.0)",
    "antlr4-python3-runtime (>=4.13.2,<5.0.0)",
    "anyio (>=4.9.0,<5.0.0)",
    "asttokens (>=3.0.0,<4.0.0)",
    "async-timeout (>=5.0.1,<6.0.0)",
    "attrs (>=25.3.0,<26.0.0)",
    "awkward (>=2.8.1,<3.0.0)",
    "awkward-cpp (>=45,<46)",
    "blinker (>=1.9.0,<2.0.0)",
    "cachetools (>=5.5.2,<6.0.0)",
    "certifi (>=2025.1.31,<2026.0.0)",
    "charset-normalizer (>=3.4.1,<4.0.0)",
    "click (>=8.1.8,<9.0.0)",
    "cloudpickle (>=3.1.1,<4.0.0)",
    "colorama (>=0.4.6,<0.5.0)",
    "colorlog (>=6.9.0,<7.0.0)",
    "comm (>=0.2.2,<0.3.0)",
    "cramjam (>=2.9.1,<3.0.0)",
    "cycler (>=0.12.1,<0.13.0)",
    "databricks-sdk (>=0.49.0,<0.50.0)",
    "debugpy (>=1.8.13,<2.0.0)",
    "decorator (>=5.2.1,<6.0.0)",
    "deprecated (>=1.2.18,<2.0.0)",
    "docker (>=7.1.0,<8.0.0)",
    "exceptiongroup (>=1.2.2,<2.0.0)",
    "executing (>=2.2.0,<3.0.0)",
    "fastapi (>=0.115.12,<0.116.0)",
    "filelock (>=3.18.0,<4.0.0)",
    "flask (>=3.1.0,<4.0.0)",
    "fonttools (>=4.56.0,<5.0.0)",
    "frozenlist (>=1.5.0,<2.0.0)",
    "fsspec (>=2025.3.0,<2026.0.0)",
    "gitdb (>=4.0.12,<5.0.0)",
    "gitpython (>=3.1.44,<4.0.0)",
    "google-auth (>=2.38.0,<3.0.0)",
    "graphene (>=3.4.3,<4.0.0)",
    "graphql-core (>=3.2.6,<4.0.0)",
    "graphql-relay (>=3.2.0,<4.0.0)",
    "greenlet (>=3.1.1,<4.0.0)",
    "h11 (>=0.14.0,<0.15.0)",
    "h5py (>=3.13.0,<4.0.0)",
    "hydra-colorlog (>=1.2.0,<2.0.0)",
    "hydra-core (>=1.3.2,<2.0.0)",
    "idna (>=3.10,<4.0)",
    "importlib-metadata (>=8.6.1,<9.0.0)",
    "ipdb (>=0.13.13,<0.14.0)",
    "ipykernel (>=6.29.5,<7.0.0)",
    "itsdangerous (>=2.2.0,<3.0.0)",
    "jedi (>=0.19.2,<0.20.0)",
    "jinja2 (>=3.1.6,<4.0.0)",
    "joblib (>=1.4.2,<2.0.0)",
    "jupyter-client (>=8.6.3,<9.0.0)",
    "jupyter-core (>=5.7.2,<6.0.0)",
    "l1trigger-datamaker @ git+https://github.com/bb511/l1trigger_datamaker.git",
    "lightning-utilities (>=0.14.2,<0.15.0)",
    "mako (>=1.3.9,<2.0.0)",
    "markdown (>=3.7,<4.0)",
    "markdown-it-py (>=3.0.0,<4.0.0)",
    "markupsafe (>=3.0.2,<4.0.0)",
    "matplotlib-inline (>=0.1.7,<0.2.0)",
    "mdurl (>=0.1.2,<0.2.0)",
    "mlflow (>=2.21.2,<3.0.0)",
    "mlflow-skinny (>=2.21.2,<3.0.0)",
    "mpmath (>=1.3.0,<2.0.0)",
    "multidict (>=6.2.0,<7.0.0)",
    "nest-asyncio (>=1.6.0,<2.0.0)",
    "omegaconf (>=2.3.0,<3.0.0)",
    "opentelemetry-api (>=1.31.1,<2.0.0)",
    "opentelemetry-sdk (>=1.31.1,<2.0.0)",
    "opentelemetry-semantic-conventions (>=0.52b1,<0.53)",
    "packaging (>=24.2,<25.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "parso (>=0.8.4,<0.9.0)",
    "pillow (>=11.1.0,<12.0.0)",
    "platformdirs (>=4.3.7,<5.0.0)",
    "prompt-toolkit (>=3.0.50,<4.0.0)",
    "propcache (>=0.3.1,<0.4.0)",
    "psutil (>=7.0.0,<8.0.0)",
    "pure-eval (>=0.2.3,<0.3.0)",
    "pyarrow (>=19.0.1,<20.0.0)",
    "pyasn1 (>=0.6.1,<0.7.0)",
    "pyasn1-modules (>=0.4.2,<0.5.0)",
    "pydantic (>=2.11.0,<3.0.0)",
    "pydantic-core (>=2.33.0,<3.0.0)",
    "pygments (>=2.19.1,<3.0.0)",
    "pyparsing (>=3.2.3,<4.0.0)",
    "python-dateutil (>=2.9.0.post0,<3.0.0)",
    "python-dotenv (>=1.1.0,<2.0.0)",
    "pytorch-lightning (>=2.5.1,<3.0.0)",
    "pytz (>=2025.2,<2026.0)",
    "pywin32 (>=310,<311)",
    "pyyaml (>=6.0.2,<7.0.0)",
    "pyzmq (>=26.3.0,<27.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "rich (>=13.9.4,<14.0.0)",
    "rootutils (>=1.0.7,<2.0.0)",
    "rsa (>=4.9,<5.0)",
    "scikit-learn (>=1.6.1,<2.0.0)",
    "six (>=1.17.0,<2.0.0)",
    "smmap (>=5.0.2,<6.0.0)",
    "sniffio (>=1.3.1,<2.0.0)",
    "sqlalchemy (>=2.0.40,<3.0.0)",
    "sqlparse (>=0.5.3,<0.6.0)",
    "stack-data (>=0.6.3,<0.7.0)",
    "starlette (>=0.46.1,<0.47.0)",
    "sympy (==1.13.1)",
    "threadpoolctl (>=3.6.0,<4.0.0)",
    "tomli (>=2.2.1,<3.0.0)",
    "torchmetrics (>=1.7.0,<2.0.0)",
    "tornado (>=6.4.2,<7.0.0)",
    "tqdm (>=4.67.1,<5.0.0)",
    "traitlets (>=5.14.3,<6.0.0)",
    "typing-extensions (>=4.13.0,<5.0.0)",
    "tzdata (>=2025.2,<2026.0)",
    "uproot (>=5.6.0,<6.0.0)",
    "urllib3 (>=2.3.0,<3.0.0)",
    "uvicorn (>=0.34.0,<0.35.0)",
    "waitress (>=3.0.2,<4.0.0)",
    "wcwidth (>=0.2.13,<0.3.0)",
    "werkzeug (>=3.1.3,<4.0.0)",
    "wrapt (>=1.17.2,<2.0.0)",
    "xxhash (>=3.5.0,<4.0.0)",
    "yarl (>=1.18.3,<2.0.0)",
    "zipp (>=3.21.0,<4.0.0)",
    "contourpy (<1.3)",
    "ipython (<8.18)",
    "kiwisolver (<1.4.8)",
    "matplotlib (<3.10.1)",
    "networkx (<3.4.2)",
    "protobuf (<6)",
    "scipy (<1.15.2)",
    "torch (>=2.6.0,<3.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
addopts = [
  "--color=yes",
  "--durations=0",
  "--strict-markers",
  "--doctest-modules",
]
filterwarnings = [
  "ignore::DeprecationWarning",
  "ignore::UserWarning",
]
log_cli = "True"
markers = [
  "slow: slow tests",
]
minversion = "6.0"
testpaths = "tests/"

[tool.coverage.report]
exclude_lines = [
    "pragma: nocover",
    "raise NotImplementedError",
    "raise NotImplementedError()",
    "if __name__ == .__main__.:",
]
