# @package evaluators

defaults:
  - base@last_evaluator: default
  - base@single_evaluator: default
  - _self_

# The basic is consistent with the basic checkpointing strategy, defined in callbacks
# directory of the config, basic.yaml file.
last_evaluator:
  strategy: last

single_evaluator:
  strategy: single
  metric_criteria:
    loss: ['min']
