# @package evaluator

defaults:
  - _self_

_target_: src.evaluation.evaluator.Evaluator
# Configure the evaluator to look at specific checkpoints and evaluate them.
# This below means take the checkpoints corresponding to the last epoch, as well as
# those checkopinted on each individual test data set, checkpointed at the minimum
# of the total loss function evaluated on each data set.
enable_model_summary: false
enable_checkpointing: false

ckpts:
  last: true
  single:
    loss: ['min']
