# AE algorithm configuration.
defaults:
  - _self_

_target_: src.algorithms.ae.AE
features: null

encoder:
  _target_: src.models.encoder.Encoder
  nodes: [117, 28, 16, 8]

decoder:
  _target_: src.models.decoder.Decoder
  nodes: [8, 24, 32, 64, 128, 117]

loss:
  _target_: src.losses.ae.ClassicAELoss
  reduction: none

optimizer:
  _partial_: true
  _target_: torch.optim.AdamW
  lr: 0.001
  weight_decay: 0.01

scheduler:
  scheduler:
    _partial_: true
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.95
