# Get the encoder and decoder configuration from model/ config directory.
defaults:
  - /model/encoder@encoder
  - /model/decoder@decoder
  - _self_

_target_: src.algorithms.ae.AE
features: null 

loss:
  _target_: src.losses.ae.ClassicAELoss
  reduction: none

optimizer:
  _partial_: true
  _target_: torch.optim.AdamW
  lr: 0.001
  betas: (0.9, 0.999)
  weight_decay: 0.01

scheduler:
  # here other attributes...
  scheduler:
    _partial_: true
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.95
