# @package algorithm

_target_: src.algorithms.vicreg.VICReg

seed: ${seed}

feature_blur:
  _target_: src.algorithms.components.augmentation.FastFeatureBlur
  prob: 0.9004016520359364
  magnitude: 0.92685112547458
  strength: 0.749655944679925

object_mask:
  _target_: src.algorithms.components.augmentation.FastObjectMask
  prob: 0.5709886168264394

lorentz_rotation:
  _target_: src.algorithms.components.augmentation.FastLorentzRotation
  _partial_: true
  prob: 0.5

model:
  _target_: src.models.components.mlp.MLP
  nodes: [57, 29, 10]
  batchnorm: false

projector:
  _target_: src.models.components.mlp.MLP
  nodes: [10, 40]
  batchnorm: true

loss:
  _target_: src.losses.vicreg.VICRegLoss
  inv_coef: 25
  rvar_coef: 25
  rcov_coef: 25

optimizer:
  _partial_: true
  _target_: torch.optim.Adam
  lr: 0.0001033146150433934
  weight_decay: 0
  betas: [0.9, 0.99]
  eps: 1e-8

scheduler:
  scheduler:
    _target_: src.optimizers.cdrw.CDRW
    _partial_: true
    lr0: 0.0001033146150433934
    s0: 32
    t_mul: 2.0
    m_mul: 0.5
    alpha: 0.0
    warmup_epochs: 10
