_target_: src.algorithms.svdd.SVDD


masking: null


features: null


encoder:
  _target_: src.models.encoder.Encoder

  nodes: [57, 28, 16, 8]
  
  batchnorm: false
  
  init_weight:
    _target_: src.utils.hydra.get_method
    path: torch.nn.init.xavier_uniform_
    
  init_bias:
    _target_: src.utils.hydra.get_method
    path: torch.nn.init.zeros_


center_init_method: mean # "mean", "zeros"


loss:
  _target_: src.losses.svdd.SVDDLoss
  nu: 0.1
  reduction: none
  weight_decay: 1e-6
  soft_boundary: false
  

optimizer:
  _partial_: true
  _target_: torch.optim.Adam
  lr: 0.001
  weight_decay: 1e-6


# scheduler:
#   # here other attributes...

#   scheduler:
#     _partial_: true
#     _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#     mode: min
#     factor: 0.5
#     patience: 10
#     min_lr: 1e-6
#   monitor: "train/loss_svdd"