# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=mnist_optuna experiment=example

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric_config: 
  AnomalyEfficiencyCallback:
    metric_name: loss/kl/full
    target_rate: 1
  direction: maximize

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  mode: "MULTIRUN" # set hydra to multirun by default if this config is attached
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: sqlite:///optuna_logs/optim_v3.db

    # name of the study to persist optimization results
    study_name: test

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: maximize

    # total number of runs that will be executed
    n_trials: 250

    # choose Optuna hyperparameter sampler
    # you can choose bayesian sampler (tpe), random search (without optimization), grid sampler, and others
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      # seed: 1234
      n_startup_trials: 15 # number of random sampling runs before optimization starts

    # define hyperparameter search space
    params:
      algorithm.optimizer._target_: choice(torch.optim.SGD,torch.optim.AdamW)
      algorithm.optimizer.lr: interval(0.00001, 0.001)
      algorithm.optimizer.weight_decay: interval(0.00001, 0.001)
      algorithm.loss.scale: choice(0.1, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1)
      data.batch_size: choice(16276, 32552, 65014)
