# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=mnist_optuna experiment=example

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric_config: 
  callback:
    name: AnomalyEfficiencyCallback
    params:
      metric_name: loss/kl/full
      target_rate: 1
  direction: maximize

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  mode: "MULTIRUN" # set hydra to multirun by default if this config is attached
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: sqlite:///optuna_logs/optim_v2.db

    # name of the study to persist optimization results
    study_name: vae_search_broad_bs16k

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: maximize

    # total number of runs that will be executed
    n_trials: 80

    # choose Optuna hyperparameter sampler
    # you can choose bayesian sampler (tpe), random search (without optimization), grid sampler, and others
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      # seed: 1234
      n_startup_trials: 60 # number of random sampling runs before optimization starts

    # define hyperparameter search space. Assumes using torch.optim.AdamW
    params:
      trainer.gradient_clip_val: choice(0.0, 0.5, 1.0, 2.0, 5.0)
      algorithm.optimizer.betas: choice([0.9, 0.999], [0.9, 0.99], [0.95, 0.999], [0.95, 0.99])
      algorithm.optimizer.eps: choice(1e-8, 1e-7, 1e-6, 1e-5)
      algorithm.optimizer.lr: tag(log, interval(1e-5, 1e-3))
      algorithm.optimizer.weight_decay: tag(log, interval(1e-10, 1e-3))
      algorithm.loss.kl_scale: tag(log, interval(1, 1000))
      algorithm.kl_warmup_frac: choice(0.0, 0.05, 0.1, 0.2, 0.3, 0.5)
      # data.batch_size: choice(4096, 16276, 65104)
