# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=mnist_optuna experiment=example

defaults:
  - override /hydra/sweeper: optuna
  # - override /hydra/sweeper/sampler: motpe
  - override /hydra/sweeper/sampler: nsgaii

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric_config: 
  callback:
    name: LossCallback
    params:
      ckpt_ds: last
      test_ds: main_test
  direction: minimize
  sec_metric:
    callback:
      name: KNNAUPRC
      params:
        ckpt_ds: null # This will be filled in with the best ckpt of the main metric.
    direction: maximize

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  mode: "MULTIRUN" # set hydra to multirun by default if this config is attached
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: sqlite:///optuna_logs/optim_v1.db

    # name of the study to persist optimization results
    study_name: vicreg_search_robustnorm_bs16k

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: [minimize, maximize]

    # total number of runs that will be executed
    n_trials: 50

    # choose Optuna hyperparameter sampler
    # you can choose bayesian sampler (tpe), random search (without optimization), grid sampler, and others
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      population_size: 50
      mutation_prob: null     # keep default (1/num_params)
      crossover_prob: 0.9     # default
      swapping_prob: 0.5      # default
      constraints_func: null  # unless you implement constraints
      # n_startup_trials: 30
      # consider_endpoints: true
      # n_ehvi_candidates: 48

    # define hyperparameter search space
    params:
      trainer.gradient_clip_val: choice(0.0, 0.5, 1.0, 2.0, 5.0)

      algorithm.optimizer.lr: tag(log, interval(1e-4, 1e-3))
      algorithm.optimizer.weight_decay: tag(log, interval(1e-6, 1e-3))
      algorithm.optimizer.betas: choice([0.9, 0.999], [0.9, 0.99], [0.95, 0.999], [0.95, 0.99])

      algorithm.scheduler.scheduler.warmup_ratio: choice(0.0, 0.01, 0.03, 0.05, 0.1)
      algorithm.scheduler.scheduler.min_lr_ratio: choice(0.0, 0.01, 0.05, 0.1)

      algorithm.feature_blur.prob: interval(0.1, 0.6)
      algorithm.feature_blur.magnitude: interval(0.1, 0.6)
      algorithm.feature_blur.strength: interval(0.1, 0.6)

      algorithm.object_mask.prob: interval(0.0, 0.5)
      algorithm.lorentz_rotation.prob: choice(0.0, 0.3, 0.6)

      algorithm.loss.var_coef: tag(log, interval(10, 100))
      algorithm.loss.cov_coef: tag(log, interval(10, 60))

      algorithm.model.out_dim: choice(16, 32, 64)
      # data.batch_size: choice(16276, 32552, 65104)
