# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=mnist_optuna experiment=example

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric_config: 
  callback:
    name: LossCallback
    params:
      loss_name: loss
  direction: minimize

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  mode: "MULTIRUN" # set hydra to multirun by default if this config is attached
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: sqlite:///optuna_logs/optim_v1.db

    # name of the study to persist optimization results
    study_name: vicreg_search_v2

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: minimize

    # total number of runs that will be executed
    n_trials: 150

    # choose Optuna hyperparameter sampler
    # you can choose bayesian sampler (tpe), random search (without optimization), grid sampler, and others
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      # seed: 1234
      n_startup_trials: 15 # number of random sampling runs before optimization starts

    # define hyperparameter search space
    params:
      algorithm.optimizer._target_: choice(torch.optim.SGD,torch.optim.AdamW)
      algorithm.optimizer.lr: tag(log, interval(1e-4, 1e-3))
      algorithm.optimizer.weight_decay: tag(log, interval(1e-5, 1e-3))
      data.batch_size: choice(16276, 32552, 65104)

      algorithm.feature_blur.prob: choice(0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0)
      algorithm.feature_blur.magnitude: choice(0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0)
      algorithm.feature_blur.strength: choice(0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0)

      algorithm.object_mask.prob: choice(0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0)

      algorithm.lorentz_rotation.prob: choice(0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0)

      algorithm.loss.inv_coef: tag(log, interval(10, 50))
      algorithm.loss.var_coef: tag(log, interval(10, 50))
      algorithm.loss.cov_coef: tag(log, interval(0.3, 3))
