# @package _global_

# Initial hyperparameter study for the vicreg algorithm.
# !!!!!! Batch size is fixed at 16384 !!!!!!!

defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: nsgaii

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric_config: 
  callback:
    name: LossCallback
    params:
      ckpt_ds: last
      test_ds: main_test
  direction: minimize
  sec_metric:
    callback:
      name: KNNAUPRC
      params:
        ckpt_ds: null # This will be filled in with the best ckpt of the main metric.
    direction: maximize


hydra:
  mode: "MULTIRUN" # set hydra to multirun by default if this config is attached
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: sqlite:///optuna_logs/optim_inputsv4.db

    # name of the study to persist optimization results
    study_name: vicreg_archnew_b16k

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: [minimize, maximize]

    # total number of runs that will be executed per process
    n_trials: 33

    # Using nsgaii sampler with the following hyperparameters:
    sampler:
      population_size: 50
      mutation_prob: null     # keep default (1/num_params)
      crossover_prob: 0.9     # default
      swapping_prob: 0.5      # default
      constraints_func: null  # unless you implement constraints

    # define vicreg hyperparameter search space
    params:
      trainer.gradient_clip_val: choice(0.0, 0.5, 1.0, 2.0, 5.0)

      algorithm.optimizer.lr: tag(log, interval(3e-5, 1e-3))
      algorithm.optimizer.weight_decay: tag(log, interval(1e-6, 1e-3))
      algorithm.optimizer.betas: choice([0.9, 0.999], [0.9, 0.99], [0.95, 0.999], [0.95, 0.99])

      algorithm.scheduler.scheduler.warmup_ratio: choice(0.0, 0.01, 0.03, 0.05, 0.1)
      algorithm.scheduler.scheduler.min_lr_ratio: choice(0.0, 0.01, 0.05, 0.1)

      algorithm.feature_blur.prob: interval(0.0, 0.9)
      algorithm.feature_blur.magnitude: interval(0.1, 0.6)
      algorithm.feature_blur.strength: interval(0.1, 0.6)

      algorithm.object_mask.prob: interval(0.0, 0.7)
      algorithm.lorentz_rotation.prob: choice(0.0, 0.3, 0.6)

      algorithm.loss.inv_coef: tag(log, interval(10, 80))
      algorithm.loss.rvar_coef: interval(0.3, 3)
      algorithm.loss.rcov_coef: interval(0.1, 2)

      algorithm.projector.out_dim: choice(32, 64, 128)
      algorithm.projector.nodes: choice([64,64], [128,128], [256,256])
      # algorithm.model.out_dim: choice(16, 32, 64)
