# @package _global_

# Initial hyperparameter study for the vicreg algorithm.
# !!!!!! Batch size is fixed at 16384 !!!!!!!

defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: motpe

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric_config: 
  callback:
    name: KNNEffs
    params:
      target_rate: 0.25
  direction: maximize
  sec_metric:
    callback:
      name: LossCallback
      params:
        ckpt_ds: null # This will get filled in by the ckpt_ds with highest KNNAUPRC.
        test_ds: main_test
    direction: minimize


hydra:
  mode: "MULTIRUN" # set hydra to multirun by default if this config is attached
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: sqlite:///optuna_logs/vicreg.db

    # name of the study to persist optimization results
    study_name: knneff_vs_loss_b16k

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: [maximize, minimize]

    # total number of runs that will be executed per process
    n_trials: 50

    # Using nsgaii sampler with the following hyperparameters:
    sampler:
      n_startup_trials: 3
      consider_endpoints: true
      n_ehvi_candidates: 128

    # define vicreg hyperparameter search space
    params:
      trainer.gradient_clip_val: choice(0.0, 1.0, 2.0)

      algorithm.optimizer.lr: tag(log, interval(3e-5, 1e-3))
      algorithm.optimizer.weight_decay: choice(1e-6, 3e-6, 1e-5, 3e-5, 1e-4, 3e-4)
      algorithm.optimizer.betas: choice([0.9, 0.999], [0.9, 0.99])

      algorithm.scheduler.scheduler.warmup_ratio: choice(0.0, 0.01, 0.03, 0.05, 0.1)
      algorithm.scheduler.scheduler.min_lr_ratio: choice(0.01, 0.05, 0.1)

      algorithm.feature_blur.prob: interval(0.0, 0.5)
      algorithm.feature_blur.magnitude: interval(0.1, 0.6)

      algorithm.object_mask.prob: interval(0.0, 0.4)
      algorithm.lorentz_rotation.prob: choice(0.0, 0.3, 0.6)

      algorithm.loss.inv_coef: tag(log, interval(10, 80))
      algorithm.loss.rvar_coef: interval(0.3, 3)
      algorithm.loss.rcov_coef: interval(0.1, 2)

      algorithm.model.nodes: choice([32], [48], [64], [32,32], [48,48], [64, 64])
      algorithm.model.out_dim: choice(16, 32, 64)
