_target_: src.models.qae.QAE

autoencoder:
  _target_: src.models.components.ae.QuantizedAutoEncoder
  input_features: 57
  encoder_nodes: [28, 15]
  decoder_nodes: [24, 32, 64, 128, 57]
  precision: [8, 5]
  use_BN: True

loss:
  _target_: src.models.losses.cylptpz.CylPtPzMAELoss

  self, norm_scales: np.ndarray, norm_biases: np.ndarray, 
                 mask: Dict[str, np.ndarray], unscale_energy: bool = False):


optimizer:
  _partial_: true
  _target_: src.models.optimizers.lion.LionOptimizer
  lr: 0.0001
  betas: (0.9, 0.99)
  weight_decay: 0.0

scheduler:
  # here other attributes...
  scheduler:
    _partial_: true
    _target_: src.models.optimizers.cdrw.CDRW
    lr0: ${model.optimizer.lr} 
    s0: 1
    t_mul: 2.0
    m_mul: 1.0
    alpha: 0.0
    warmup_epochs: 10
    last_epoch: -1

# compile model for faster training
compile: false