# @package evaluator.trainer_kwargs

defaults:
  - _self_

_target_: src.evaluation.evaluator.Evaluator
default_root_dir: ${paths.output_dir}
accelerator: gpu
devices: [0]
enable_model_summary: false

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: true
