_target_: src.models.components.masking.ParticleMasking

constituents: ${data.data_awkward2torch.nconst}
objects_features: ${data.data_mlready.select_features}

# Masking probabilities per object type
mask_probs:
  muons: 0.15
  egammas: 0.15
  jets: 0.15
  ET: 0.05
  MET: 0.05

# Value to replace masked features with
mask_value: 0.0

# Only apply masking during training
training_only: true
