_target_: src.callbacks.model_checkpoint.SingleDatasetModelCheckpoint
# _target_: src.callbacks.model_checkpoint.LeaveOneOutModelCheckpoint
dirpath: ${paths.output_dir}/checkpoints
filename: '{epoch:02d}-{step}'
loss_name: loss
save_top_k: 1
mode: max
save_last: true
