_target_: src.callbacks.model_checkpoint.SingleDatasetModelCheckpoint
# _target_: src.callbacks.model_checkpoint.LeaveOneOutModelCheckpoint
dirpath: ${paths.output_dir}/checkpoints
filename: '{epoch:02d}-{step}'
metric_name: loss_total_full_rate0.3
save_top_k: 1
mode: min
save_last: true