model_checkpoint_i:
  _target_: src.callbacks.model_checkpoint.SingleDatasetModelCheckpoint
  # dirpath: ${paths.output_dir}/checkpoints
  dirpath: ${paths.root_dir}/checkpoints/scan_lr=${scan.lr}_alpha=${scan.alpha}/
  filename: 'e={epoch:02d}-s={step}'
  metric_name: loss/kl
  ds_keys_to_skip: null
  save_top_k: 1
  mode: min
  save_last: true