# @package _global_

defaults:
  - _self_
  - data: L1AD
  - algorithm: vae
  - trainer: default
  - paths: default
  - callbacks: default
  - logger: none
  - extras: default
  - hydra: default

  # Pass this from the script:
  - experiment: null

  # Override from experiment:
  - override /callbacks: eval
  - override /logger: none


task_name: "eval"

algorithm:
  masking: null
  features: null
