model_checkpoint_cap_baseline:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: '${paths.root_dir}/checkpoints/${experiment_name}/${run_name}/cap'
  filename: 'ds=baseline__value={cap/val/baseline:.1f}__epoch={epoch}'
  monitor: cap/val/baseline
  save_top_k: 1
  mode: max
  save_last: false


model_checkpoint_cap_background0:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: '${paths.root_dir}/checkpoints/${experiment_name}/${run_name}/cap'
  filename: 'ds=background0__value={cap/val/background0:.1f}__epoch={epoch}'
  monitor: cap/val/background0
  save_top_k: 1
  mode: max
  save_last: false


model_checkpoint_cap_background1:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: '${paths.root_dir}/checkpoints/${experiment_name}/${run_name}/cap'
  filename: 'ds=background1__value={cap/val/background1:.1f}__epoch={epoch}'
  monitor: cap/val/background1
  save_top_k: 1
  mode: max
  save_last: false