model_checkpoint_cap_baseline:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: '${paths.root_dir}/checkpoints/${scan_dirname: ${scan}}/cap/'
  filename: 'baseline-{epoch}-{step}'
  monitor: cap/val/baseline
  save_top_k: 1
  mode: max
  save_last: false


model_checkpoint_cap_background0:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: '${paths.root_dir}/checkpoints/${scan_dirname: ${scan}}/cap/'
  filename: 'background0-{epoch}-{step}'
  monitor: cap/val/background0
  save_top_k: 1
  mode: max
  save_last: false


model_checkpoint_cap_background1:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: '${paths.root_dir}/checkpoints/${scan_dirname: ${scan}}/cap/'
  filename: 'background1-{epoch}-{step}'
  monitor: cap/val/background1
  save_top_k: 1
  mode: max
  save_last: false