# @package evaluator_callbacks.metrics

# The metric names need be specified like they are given by the model.
_target_: src.evaluation.callbacks.knn_rate.KNNEffs
output_name: "vicreg_rep_data"
k: 10
target_rates: [0.01, 0.1, 0.25, 0.5, 1]
bc_rate: 28608.8064
reference_sample_size: 40_000
bkg_sample_size: 500_000
log_raw_mlflow: true
ds:
  - GluGluHTo2B_Par-MH-125
  - GluGluHto2G_Par-MH-125
  - GluGluHto2G_Par-MH-90
  - GluGluHto2Tau_Par-MH-125
  - GluGlutoHHto2B2WtoLNu2Q_Par-c2-0-kl-1-kt-1
